# backend internal service
apiVersion: v1
kind: Service
metadata:
  name: backend-service-internal
  namespace: three-tier-app
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http # ✅ add port name
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
