# backend internal service
apiVersion: v1
kind: Service
metadata:
  name: backend-service-internal
  namespace: three-tier-app
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http # ✅ add port name
      port: 3000
      targetPort: 3000
  type: ClusterIP

---



# MySQL internal service (already ClusterIP, optional rename)
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-internal
  namespace: three-tier-app
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
