apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter-service
  namespace: three-tier-app
  labels:
    app: mysqld-exporter
spec:
  selector:
    app: mysqld-exporter
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
  type: ClusterIP
