apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.17.0
          args:
            - "--config.my-cnf="
            - "--datasource=$(DATA_SOURCE_NAME)"
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secret
                  key: DATA_SOURCE_NAME
