apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.17.0
          ports:
            - name: metrics
              containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-exporter-secret
                  key: DATA_SOURCE_NAME
          args:
            - "--collect.global_status"
            - "--collect.global_variables"
            - "--collect.info_schema.tables"
            - "--collect.info_schema.processlist"
            - "--collect.performance_schema.eventsstatements"
            - "--collect.auto_increment.columns"
