apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: three-tier-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # ⚠️ only for local/minikube. On cloud use EBS/EFS/PD
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: three-tier-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
