grafana:
  adminUser: admin
  adminPassword: admin123 # change this later
  service:
    type: NodePort
    nodePort: 32000 # access Grafana at http://<EC2-IP>:32000

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 32001 # access Prometheus at http://<EC2-IP>:32001
