apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - three-tier-app # fix typo here
  endpoints:
    - port: 3000 # matches internal ClusterIP service
      path: /metrics
      interval: 15s
