apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: mysqld-exporter
  namespaceSelector:
    matchNames:
      - three-tier-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
