apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prom-stack # must match Helm release
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - three-tier-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
